// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: map_renderer.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_map_5frenderer_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_map_5frenderer_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021005 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "svg.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_map_5frenderer_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_map_5frenderer_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_map_5frenderer_2eproto;
namespace transport_catalogue_proto {
class MapRenderer;
struct MapRendererDefaultTypeInternal;
extern MapRendererDefaultTypeInternal _MapRenderer_default_instance_;
class RenderSettings;
struct RenderSettingsDefaultTypeInternal;
extern RenderSettingsDefaultTypeInternal _RenderSettings_default_instance_;
class StopCoords;
struct StopCoordsDefaultTypeInternal;
extern StopCoordsDefaultTypeInternal _StopCoords_default_instance_;
}  // namespace transport_catalogue_proto
PROTOBUF_NAMESPACE_OPEN
template<> ::transport_catalogue_proto::MapRenderer* Arena::CreateMaybeMessage<::transport_catalogue_proto::MapRenderer>(Arena*);
template<> ::transport_catalogue_proto::RenderSettings* Arena::CreateMaybeMessage<::transport_catalogue_proto::RenderSettings>(Arena*);
template<> ::transport_catalogue_proto::StopCoords* Arena::CreateMaybeMessage<::transport_catalogue_proto::StopCoords>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace transport_catalogue_proto {

// ===================================================================

class RenderSettings final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:transport_catalogue_proto.RenderSettings) */ {
 public:
  inline RenderSettings() : RenderSettings(nullptr) {}
  ~RenderSettings() override;
  explicit PROTOBUF_CONSTEXPR RenderSettings(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  RenderSettings(const RenderSettings& from);
  RenderSettings(RenderSettings&& from) noexcept
    : RenderSettings() {
    *this = ::std::move(from);
  }

  inline RenderSettings& operator=(const RenderSettings& from) {
    CopyFrom(from);
    return *this;
  }
  inline RenderSettings& operator=(RenderSettings&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const RenderSettings& default_instance() {
    return *internal_default_instance();
  }
  static inline const RenderSettings* internal_default_instance() {
    return reinterpret_cast<const RenderSettings*>(
               &_RenderSettings_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(RenderSettings& a, RenderSettings& b) {
    a.Swap(&b);
  }
  inline void Swap(RenderSettings* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(RenderSettings* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  RenderSettings* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<RenderSettings>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const RenderSettings& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const RenderSettings& from) {
    RenderSettings::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(RenderSettings* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "transport_catalogue_proto.RenderSettings";
  }
  protected:
  explicit RenderSettings(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kPaletteFieldNumber = 4,
    kUnderlayerColorFieldNumber = 6,
    kBusLabelOffsetFieldNumber = 9,
    kStopLabelOffsetFieldNumber = 11,
    kMaxWidthFieldNumber = 1,
    kMaxHeightFieldNumber = 2,
    kPaddingFieldNumber = 3,
    kLineWidthFieldNumber = 5,
    kUnderlayerWidthFieldNumber = 7,
    kStopRadiusFieldNumber = 8,
    kBusLabelFontSizeFieldNumber = 10,
    kStopLabelFontSizeFieldNumber = 12,
  };
  // repeated .svg_proto.Color palette = 4;
  int palette_size() const;
  private:
  int _internal_palette_size() const;
  public:
  void clear_palette();
  ::svg_proto::Color* mutable_palette(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::svg_proto::Color >*
      mutable_palette();
  private:
  const ::svg_proto::Color& _internal_palette(int index) const;
  ::svg_proto::Color* _internal_add_palette();
  public:
  const ::svg_proto::Color& palette(int index) const;
  ::svg_proto::Color* add_palette();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::svg_proto::Color >&
      palette() const;

  // .svg_proto.Color underlayer_color = 6;
  bool has_underlayer_color() const;
  private:
  bool _internal_has_underlayer_color() const;
  public:
  void clear_underlayer_color();
  const ::svg_proto::Color& underlayer_color() const;
  PROTOBUF_NODISCARD ::svg_proto::Color* release_underlayer_color();
  ::svg_proto::Color* mutable_underlayer_color();
  void set_allocated_underlayer_color(::svg_proto::Color* underlayer_color);
  private:
  const ::svg_proto::Color& _internal_underlayer_color() const;
  ::svg_proto::Color* _internal_mutable_underlayer_color();
  public:
  void unsafe_arena_set_allocated_underlayer_color(
      ::svg_proto::Color* underlayer_color);
  ::svg_proto::Color* unsafe_arena_release_underlayer_color();

  // .svg_proto.Point bus_label_offset = 9;
  bool has_bus_label_offset() const;
  private:
  bool _internal_has_bus_label_offset() const;
  public:
  void clear_bus_label_offset();
  const ::svg_proto::Point& bus_label_offset() const;
  PROTOBUF_NODISCARD ::svg_proto::Point* release_bus_label_offset();
  ::svg_proto::Point* mutable_bus_label_offset();
  void set_allocated_bus_label_offset(::svg_proto::Point* bus_label_offset);
  private:
  const ::svg_proto::Point& _internal_bus_label_offset() const;
  ::svg_proto::Point* _internal_mutable_bus_label_offset();
  public:
  void unsafe_arena_set_allocated_bus_label_offset(
      ::svg_proto::Point* bus_label_offset);
  ::svg_proto::Point* unsafe_arena_release_bus_label_offset();

  // .svg_proto.Point stop_label_offset = 11;
  bool has_stop_label_offset() const;
  private:
  bool _internal_has_stop_label_offset() const;
  public:
  void clear_stop_label_offset();
  const ::svg_proto::Point& stop_label_offset() const;
  PROTOBUF_NODISCARD ::svg_proto::Point* release_stop_label_offset();
  ::svg_proto::Point* mutable_stop_label_offset();
  void set_allocated_stop_label_offset(::svg_proto::Point* stop_label_offset);
  private:
  const ::svg_proto::Point& _internal_stop_label_offset() const;
  ::svg_proto::Point* _internal_mutable_stop_label_offset();
  public:
  void unsafe_arena_set_allocated_stop_label_offset(
      ::svg_proto::Point* stop_label_offset);
  ::svg_proto::Point* unsafe_arena_release_stop_label_offset();

  // double max_width = 1;
  void clear_max_width();
  double max_width() const;
  void set_max_width(double value);
  private:
  double _internal_max_width() const;
  void _internal_set_max_width(double value);
  public:

  // double max_height = 2;
  void clear_max_height();
  double max_height() const;
  void set_max_height(double value);
  private:
  double _internal_max_height() const;
  void _internal_set_max_height(double value);
  public:

  // double padding = 3;
  void clear_padding();
  double padding() const;
  void set_padding(double value);
  private:
  double _internal_padding() const;
  void _internal_set_padding(double value);
  public:

  // double line_width = 5;
  void clear_line_width();
  double line_width() const;
  void set_line_width(double value);
  private:
  double _internal_line_width() const;
  void _internal_set_line_width(double value);
  public:

  // double underlayer_width = 7;
  void clear_underlayer_width();
  double underlayer_width() const;
  void set_underlayer_width(double value);
  private:
  double _internal_underlayer_width() const;
  void _internal_set_underlayer_width(double value);
  public:

  // double stop_radius = 8;
  void clear_stop_radius();
  double stop_radius() const;
  void set_stop_radius(double value);
  private:
  double _internal_stop_radius() const;
  void _internal_set_stop_radius(double value);
  public:

  // int32 bus_label_font_size = 10;
  void clear_bus_label_font_size();
  int32_t bus_label_font_size() const;
  void set_bus_label_font_size(int32_t value);
  private:
  int32_t _internal_bus_label_font_size() const;
  void _internal_set_bus_label_font_size(int32_t value);
  public:

  // int32 stop_label_font_size = 12;
  void clear_stop_label_font_size();
  int32_t stop_label_font_size() const;
  void set_stop_label_font_size(int32_t value);
  private:
  int32_t _internal_stop_label_font_size() const;
  void _internal_set_stop_label_font_size(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:transport_catalogue_proto.RenderSettings)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::svg_proto::Color > palette_;
    ::svg_proto::Color* underlayer_color_;
    ::svg_proto::Point* bus_label_offset_;
    ::svg_proto::Point* stop_label_offset_;
    double max_width_;
    double max_height_;
    double padding_;
    double line_width_;
    double underlayer_width_;
    double stop_radius_;
    int32_t bus_label_font_size_;
    int32_t stop_label_font_size_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_map_5frenderer_2eproto;
};
// -------------------------------------------------------------------

class StopCoords final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:transport_catalogue_proto.StopCoords) */ {
 public:
  inline StopCoords() : StopCoords(nullptr) {}
  ~StopCoords() override;
  explicit PROTOBUF_CONSTEXPR StopCoords(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  StopCoords(const StopCoords& from);
  StopCoords(StopCoords&& from) noexcept
    : StopCoords() {
    *this = ::std::move(from);
  }

  inline StopCoords& operator=(const StopCoords& from) {
    CopyFrom(from);
    return *this;
  }
  inline StopCoords& operator=(StopCoords&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const StopCoords& default_instance() {
    return *internal_default_instance();
  }
  static inline const StopCoords* internal_default_instance() {
    return reinterpret_cast<const StopCoords*>(
               &_StopCoords_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(StopCoords& a, StopCoords& b) {
    a.Swap(&b);
  }
  inline void Swap(StopCoords* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(StopCoords* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  StopCoords* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<StopCoords>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const StopCoords& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const StopCoords& from) {
    StopCoords::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(StopCoords* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "transport_catalogue_proto.StopCoords";
  }
  protected:
  explicit StopCoords(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kPointFieldNumber = 2,
    kStopFieldNumber = 1,
  };
  // .svg_proto.Point point = 2;
  bool has_point() const;
  private:
  bool _internal_has_point() const;
  public:
  void clear_point();
  const ::svg_proto::Point& point() const;
  PROTOBUF_NODISCARD ::svg_proto::Point* release_point();
  ::svg_proto::Point* mutable_point();
  void set_allocated_point(::svg_proto::Point* point);
  private:
  const ::svg_proto::Point& _internal_point() const;
  ::svg_proto::Point* _internal_mutable_point();
  public:
  void unsafe_arena_set_allocated_point(
      ::svg_proto::Point* point);
  ::svg_proto::Point* unsafe_arena_release_point();

  // uint32 stop = 1;
  void clear_stop();
  uint32_t stop() const;
  void set_stop(uint32_t value);
  private:
  uint32_t _internal_stop() const;
  void _internal_set_stop(uint32_t value);
  public:

  // @@protoc_insertion_point(class_scope:transport_catalogue_proto.StopCoords)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::svg_proto::Point* point_;
    uint32_t stop_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_map_5frenderer_2eproto;
};
// -------------------------------------------------------------------

class MapRenderer final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:transport_catalogue_proto.MapRenderer) */ {
 public:
  inline MapRenderer() : MapRenderer(nullptr) {}
  ~MapRenderer() override;
  explicit PROTOBUF_CONSTEXPR MapRenderer(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  MapRenderer(const MapRenderer& from);
  MapRenderer(MapRenderer&& from) noexcept
    : MapRenderer() {
    *this = ::std::move(from);
  }

  inline MapRenderer& operator=(const MapRenderer& from) {
    CopyFrom(from);
    return *this;
  }
  inline MapRenderer& operator=(MapRenderer&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const MapRenderer& default_instance() {
    return *internal_default_instance();
  }
  static inline const MapRenderer* internal_default_instance() {
    return reinterpret_cast<const MapRenderer*>(
               &_MapRenderer_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(MapRenderer& a, MapRenderer& b) {
    a.Swap(&b);
  }
  inline void Swap(MapRenderer* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(MapRenderer* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  MapRenderer* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<MapRenderer>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const MapRenderer& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const MapRenderer& from) {
    MapRenderer::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(MapRenderer* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "transport_catalogue_proto.MapRenderer";
  }
  protected:
  explicit MapRenderer(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kStopsCoordsFieldNumber = 2,
    kRenderSettingsFieldNumber = 1,
  };
  // repeated .transport_catalogue_proto.StopCoords stops_coords = 2;
  int stops_coords_size() const;
  private:
  int _internal_stops_coords_size() const;
  public:
  void clear_stops_coords();
  ::transport_catalogue_proto::StopCoords* mutable_stops_coords(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::transport_catalogue_proto::StopCoords >*
      mutable_stops_coords();
  private:
  const ::transport_catalogue_proto::StopCoords& _internal_stops_coords(int index) const;
  ::transport_catalogue_proto::StopCoords* _internal_add_stops_coords();
  public:
  const ::transport_catalogue_proto::StopCoords& stops_coords(int index) const;
  ::transport_catalogue_proto::StopCoords* add_stops_coords();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::transport_catalogue_proto::StopCoords >&
      stops_coords() const;

  // .transport_catalogue_proto.RenderSettings render_settings = 1;
  bool has_render_settings() const;
  private:
  bool _internal_has_render_settings() const;
  public:
  void clear_render_settings();
  const ::transport_catalogue_proto::RenderSettings& render_settings() const;
  PROTOBUF_NODISCARD ::transport_catalogue_proto::RenderSettings* release_render_settings();
  ::transport_catalogue_proto::RenderSettings* mutable_render_settings();
  void set_allocated_render_settings(::transport_catalogue_proto::RenderSettings* render_settings);
  private:
  const ::transport_catalogue_proto::RenderSettings& _internal_render_settings() const;
  ::transport_catalogue_proto::RenderSettings* _internal_mutable_render_settings();
  public:
  void unsafe_arena_set_allocated_render_settings(
      ::transport_catalogue_proto::RenderSettings* render_settings);
  ::transport_catalogue_proto::RenderSettings* unsafe_arena_release_render_settings();

  // @@protoc_insertion_point(class_scope:transport_catalogue_proto.MapRenderer)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::transport_catalogue_proto::StopCoords > stops_coords_;
    ::transport_catalogue_proto::RenderSettings* render_settings_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_map_5frenderer_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// RenderSettings

// double max_width = 1;
inline void RenderSettings::clear_max_width() {
  _impl_.max_width_ = 0;
}
inline double RenderSettings::_internal_max_width() const {
  return _impl_.max_width_;
}
inline double RenderSettings::max_width() const {
  // @@protoc_insertion_point(field_get:transport_catalogue_proto.RenderSettings.max_width)
  return _internal_max_width();
}
inline void RenderSettings::_internal_set_max_width(double value) {
  
  _impl_.max_width_ = value;
}
inline void RenderSettings::set_max_width(double value) {
  _internal_set_max_width(value);
  // @@protoc_insertion_point(field_set:transport_catalogue_proto.RenderSettings.max_width)
}

// double max_height = 2;
inline void RenderSettings::clear_max_height() {
  _impl_.max_height_ = 0;
}
inline double RenderSettings::_internal_max_height() const {
  return _impl_.max_height_;
}
inline double RenderSettings::max_height() const {
  // @@protoc_insertion_point(field_get:transport_catalogue_proto.RenderSettings.max_height)
  return _internal_max_height();
}
inline void RenderSettings::_internal_set_max_height(double value) {
  
  _impl_.max_height_ = value;
}
inline void RenderSettings::set_max_height(double value) {
  _internal_set_max_height(value);
  // @@protoc_insertion_point(field_set:transport_catalogue_proto.RenderSettings.max_height)
}

// double padding = 3;
inline void RenderSettings::clear_padding() {
  _impl_.padding_ = 0;
}
inline double RenderSettings::_internal_padding() const {
  return _impl_.padding_;
}
inline double RenderSettings::padding() const {
  // @@protoc_insertion_point(field_get:transport_catalogue_proto.RenderSettings.padding)
  return _internal_padding();
}
inline void RenderSettings::_internal_set_padding(double value) {
  
  _impl_.padding_ = value;
}
inline void RenderSettings::set_padding(double value) {
  _internal_set_padding(value);
  // @@protoc_insertion_point(field_set:transport_catalogue_proto.RenderSettings.padding)
}

// repeated .svg_proto.Color palette = 4;
inline int RenderSettings::_internal_palette_size() const {
  return _impl_.palette_.size();
}
inline int RenderSettings::palette_size() const {
  return _internal_palette_size();
}
inline ::svg_proto::Color* RenderSettings::mutable_palette(int index) {
  // @@protoc_insertion_point(field_mutable:transport_catalogue_proto.RenderSettings.palette)
  return _impl_.palette_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::svg_proto::Color >*
RenderSettings::mutable_palette() {
  // @@protoc_insertion_point(field_mutable_list:transport_catalogue_proto.RenderSettings.palette)
  return &_impl_.palette_;
}
inline const ::svg_proto::Color& RenderSettings::_internal_palette(int index) const {
  return _impl_.palette_.Get(index);
}
inline const ::svg_proto::Color& RenderSettings::palette(int index) const {
  // @@protoc_insertion_point(field_get:transport_catalogue_proto.RenderSettings.palette)
  return _internal_palette(index);
}
inline ::svg_proto::Color* RenderSettings::_internal_add_palette() {
  return _impl_.palette_.Add();
}
inline ::svg_proto::Color* RenderSettings::add_palette() {
  ::svg_proto::Color* _add = _internal_add_palette();
  // @@protoc_insertion_point(field_add:transport_catalogue_proto.RenderSettings.palette)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::svg_proto::Color >&
RenderSettings::palette() const {
  // @@protoc_insertion_point(field_list:transport_catalogue_proto.RenderSettings.palette)
  return _impl_.palette_;
}

// double line_width = 5;
inline void RenderSettings::clear_line_width() {
  _impl_.line_width_ = 0;
}
inline double RenderSettings::_internal_line_width() const {
  return _impl_.line_width_;
}
inline double RenderSettings::line_width() const {
  // @@protoc_insertion_point(field_get:transport_catalogue_proto.RenderSettings.line_width)
  return _internal_line_width();
}
inline void RenderSettings::_internal_set_line_width(double value) {
  
  _impl_.line_width_ = value;
}
inline void RenderSettings::set_line_width(double value) {
  _internal_set_line_width(value);
  // @@protoc_insertion_point(field_set:transport_catalogue_proto.RenderSettings.line_width)
}

// .svg_proto.Color underlayer_color = 6;
inline bool RenderSettings::_internal_has_underlayer_color() const {
  return this != internal_default_instance() && _impl_.underlayer_color_ != nullptr;
}
inline bool RenderSettings::has_underlayer_color() const {
  return _internal_has_underlayer_color();
}
inline const ::svg_proto::Color& RenderSettings::_internal_underlayer_color() const {
  const ::svg_proto::Color* p = _impl_.underlayer_color_;
  return p != nullptr ? *p : reinterpret_cast<const ::svg_proto::Color&>(
      ::svg_proto::_Color_default_instance_);
}
inline const ::svg_proto::Color& RenderSettings::underlayer_color() const {
  // @@protoc_insertion_point(field_get:transport_catalogue_proto.RenderSettings.underlayer_color)
  return _internal_underlayer_color();
}
inline void RenderSettings::unsafe_arena_set_allocated_underlayer_color(
    ::svg_proto::Color* underlayer_color) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.underlayer_color_);
  }
  _impl_.underlayer_color_ = underlayer_color;
  if (underlayer_color) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:transport_catalogue_proto.RenderSettings.underlayer_color)
}
inline ::svg_proto::Color* RenderSettings::release_underlayer_color() {
  
  ::svg_proto::Color* temp = _impl_.underlayer_color_;
  _impl_.underlayer_color_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::svg_proto::Color* RenderSettings::unsafe_arena_release_underlayer_color() {
  // @@protoc_insertion_point(field_release:transport_catalogue_proto.RenderSettings.underlayer_color)
  
  ::svg_proto::Color* temp = _impl_.underlayer_color_;
  _impl_.underlayer_color_ = nullptr;
  return temp;
}
inline ::svg_proto::Color* RenderSettings::_internal_mutable_underlayer_color() {
  
  if (_impl_.underlayer_color_ == nullptr) {
    auto* p = CreateMaybeMessage<::svg_proto::Color>(GetArenaForAllocation());
    _impl_.underlayer_color_ = p;
  }
  return _impl_.underlayer_color_;
}
inline ::svg_proto::Color* RenderSettings::mutable_underlayer_color() {
  ::svg_proto::Color* _msg = _internal_mutable_underlayer_color();
  // @@protoc_insertion_point(field_mutable:transport_catalogue_proto.RenderSettings.underlayer_color)
  return _msg;
}
inline void RenderSettings::set_allocated_underlayer_color(::svg_proto::Color* underlayer_color) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.underlayer_color_);
  }
  if (underlayer_color) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(underlayer_color));
    if (message_arena != submessage_arena) {
      underlayer_color = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, underlayer_color, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.underlayer_color_ = underlayer_color;
  // @@protoc_insertion_point(field_set_allocated:transport_catalogue_proto.RenderSettings.underlayer_color)
}

// double underlayer_width = 7;
inline void RenderSettings::clear_underlayer_width() {
  _impl_.underlayer_width_ = 0;
}
inline double RenderSettings::_internal_underlayer_width() const {
  return _impl_.underlayer_width_;
}
inline double RenderSettings::underlayer_width() const {
  // @@protoc_insertion_point(field_get:transport_catalogue_proto.RenderSettings.underlayer_width)
  return _internal_underlayer_width();
}
inline void RenderSettings::_internal_set_underlayer_width(double value) {
  
  _impl_.underlayer_width_ = value;
}
inline void RenderSettings::set_underlayer_width(double value) {
  _internal_set_underlayer_width(value);
  // @@protoc_insertion_point(field_set:transport_catalogue_proto.RenderSettings.underlayer_width)
}

// double stop_radius = 8;
inline void RenderSettings::clear_stop_radius() {
  _impl_.stop_radius_ = 0;
}
inline double RenderSettings::_internal_stop_radius() const {
  return _impl_.stop_radius_;
}
inline double RenderSettings::stop_radius() const {
  // @@protoc_insertion_point(field_get:transport_catalogue_proto.RenderSettings.stop_radius)
  return _internal_stop_radius();
}
inline void RenderSettings::_internal_set_stop_radius(double value) {
  
  _impl_.stop_radius_ = value;
}
inline void RenderSettings::set_stop_radius(double value) {
  _internal_set_stop_radius(value);
  // @@protoc_insertion_point(field_set:transport_catalogue_proto.RenderSettings.stop_radius)
}

// .svg_proto.Point bus_label_offset = 9;
inline bool RenderSettings::_internal_has_bus_label_offset() const {
  return this != internal_default_instance() && _impl_.bus_label_offset_ != nullptr;
}
inline bool RenderSettings::has_bus_label_offset() const {
  return _internal_has_bus_label_offset();
}
inline const ::svg_proto::Point& RenderSettings::_internal_bus_label_offset() const {
  const ::svg_proto::Point* p = _impl_.bus_label_offset_;
  return p != nullptr ? *p : reinterpret_cast<const ::svg_proto::Point&>(
      ::svg_proto::_Point_default_instance_);
}
inline const ::svg_proto::Point& RenderSettings::bus_label_offset() const {
  // @@protoc_insertion_point(field_get:transport_catalogue_proto.RenderSettings.bus_label_offset)
  return _internal_bus_label_offset();
}
inline void RenderSettings::unsafe_arena_set_allocated_bus_label_offset(
    ::svg_proto::Point* bus_label_offset) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.bus_label_offset_);
  }
  _impl_.bus_label_offset_ = bus_label_offset;
  if (bus_label_offset) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:transport_catalogue_proto.RenderSettings.bus_label_offset)
}
inline ::svg_proto::Point* RenderSettings::release_bus_label_offset() {
  
  ::svg_proto::Point* temp = _impl_.bus_label_offset_;
  _impl_.bus_label_offset_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::svg_proto::Point* RenderSettings::unsafe_arena_release_bus_label_offset() {
  // @@protoc_insertion_point(field_release:transport_catalogue_proto.RenderSettings.bus_label_offset)
  
  ::svg_proto::Point* temp = _impl_.bus_label_offset_;
  _impl_.bus_label_offset_ = nullptr;
  return temp;
}
inline ::svg_proto::Point* RenderSettings::_internal_mutable_bus_label_offset() {
  
  if (_impl_.bus_label_offset_ == nullptr) {
    auto* p = CreateMaybeMessage<::svg_proto::Point>(GetArenaForAllocation());
    _impl_.bus_label_offset_ = p;
  }
  return _impl_.bus_label_offset_;
}
inline ::svg_proto::Point* RenderSettings::mutable_bus_label_offset() {
  ::svg_proto::Point* _msg = _internal_mutable_bus_label_offset();
  // @@protoc_insertion_point(field_mutable:transport_catalogue_proto.RenderSettings.bus_label_offset)
  return _msg;
}
inline void RenderSettings::set_allocated_bus_label_offset(::svg_proto::Point* bus_label_offset) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.bus_label_offset_);
  }
  if (bus_label_offset) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(bus_label_offset));
    if (message_arena != submessage_arena) {
      bus_label_offset = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, bus_label_offset, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.bus_label_offset_ = bus_label_offset;
  // @@protoc_insertion_point(field_set_allocated:transport_catalogue_proto.RenderSettings.bus_label_offset)
}

// int32 bus_label_font_size = 10;
inline void RenderSettings::clear_bus_label_font_size() {
  _impl_.bus_label_font_size_ = 0;
}
inline int32_t RenderSettings::_internal_bus_label_font_size() const {
  return _impl_.bus_label_font_size_;
}
inline int32_t RenderSettings::bus_label_font_size() const {
  // @@protoc_insertion_point(field_get:transport_catalogue_proto.RenderSettings.bus_label_font_size)
  return _internal_bus_label_font_size();
}
inline void RenderSettings::_internal_set_bus_label_font_size(int32_t value) {
  
  _impl_.bus_label_font_size_ = value;
}
inline void RenderSettings::set_bus_label_font_size(int32_t value) {
  _internal_set_bus_label_font_size(value);
  // @@protoc_insertion_point(field_set:transport_catalogue_proto.RenderSettings.bus_label_font_size)
}

// .svg_proto.Point stop_label_offset = 11;
inline bool RenderSettings::_internal_has_stop_label_offset() const {
  return this != internal_default_instance() && _impl_.stop_label_offset_ != nullptr;
}
inline bool RenderSettings::has_stop_label_offset() const {
  return _internal_has_stop_label_offset();
}
inline const ::svg_proto::Point& RenderSettings::_internal_stop_label_offset() const {
  const ::svg_proto::Point* p = _impl_.stop_label_offset_;
  return p != nullptr ? *p : reinterpret_cast<const ::svg_proto::Point&>(
      ::svg_proto::_Point_default_instance_);
}
inline const ::svg_proto::Point& RenderSettings::stop_label_offset() const {
  // @@protoc_insertion_point(field_get:transport_catalogue_proto.RenderSettings.stop_label_offset)
  return _internal_stop_label_offset();
}
inline void RenderSettings::unsafe_arena_set_allocated_stop_label_offset(
    ::svg_proto::Point* stop_label_offset) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.stop_label_offset_);
  }
  _impl_.stop_label_offset_ = stop_label_offset;
  if (stop_label_offset) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:transport_catalogue_proto.RenderSettings.stop_label_offset)
}
inline ::svg_proto::Point* RenderSettings::release_stop_label_offset() {
  
  ::svg_proto::Point* temp = _impl_.stop_label_offset_;
  _impl_.stop_label_offset_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::svg_proto::Point* RenderSettings::unsafe_arena_release_stop_label_offset() {
  // @@protoc_insertion_point(field_release:transport_catalogue_proto.RenderSettings.stop_label_offset)
  
  ::svg_proto::Point* temp = _impl_.stop_label_offset_;
  _impl_.stop_label_offset_ = nullptr;
  return temp;
}
inline ::svg_proto::Point* RenderSettings::_internal_mutable_stop_label_offset() {
  
  if (_impl_.stop_label_offset_ == nullptr) {
    auto* p = CreateMaybeMessage<::svg_proto::Point>(GetArenaForAllocation());
    _impl_.stop_label_offset_ = p;
  }
  return _impl_.stop_label_offset_;
}
inline ::svg_proto::Point* RenderSettings::mutable_stop_label_offset() {
  ::svg_proto::Point* _msg = _internal_mutable_stop_label_offset();
  // @@protoc_insertion_point(field_mutable:transport_catalogue_proto.RenderSettings.stop_label_offset)
  return _msg;
}
inline void RenderSettings::set_allocated_stop_label_offset(::svg_proto::Point* stop_label_offset) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.stop_label_offset_);
  }
  if (stop_label_offset) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(stop_label_offset));
    if (message_arena != submessage_arena) {
      stop_label_offset = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, stop_label_offset, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.stop_label_offset_ = stop_label_offset;
  // @@protoc_insertion_point(field_set_allocated:transport_catalogue_proto.RenderSettings.stop_label_offset)
}

// int32 stop_label_font_size = 12;
inline void RenderSettings::clear_stop_label_font_size() {
  _impl_.stop_label_font_size_ = 0;
}
inline int32_t RenderSettings::_internal_stop_label_font_size() const {
  return _impl_.stop_label_font_size_;
}
inline int32_t RenderSettings::stop_label_font_size() const {
  // @@protoc_insertion_point(field_get:transport_catalogue_proto.RenderSettings.stop_label_font_size)
  return _internal_stop_label_font_size();
}
inline void RenderSettings::_internal_set_stop_label_font_size(int32_t value) {
  
  _impl_.stop_label_font_size_ = value;
}
inline void RenderSettings::set_stop_label_font_size(int32_t value) {
  _internal_set_stop_label_font_size(value);
  // @@protoc_insertion_point(field_set:transport_catalogue_proto.RenderSettings.stop_label_font_size)
}

// -------------------------------------------------------------------

// StopCoords

// uint32 stop = 1;
inline void StopCoords::clear_stop() {
  _impl_.stop_ = 0u;
}
inline uint32_t StopCoords::_internal_stop() const {
  return _impl_.stop_;
}
inline uint32_t StopCoords::stop() const {
  // @@protoc_insertion_point(field_get:transport_catalogue_proto.StopCoords.stop)
  return _internal_stop();
}
inline void StopCoords::_internal_set_stop(uint32_t value) {
  
  _impl_.stop_ = value;
}
inline void StopCoords::set_stop(uint32_t value) {
  _internal_set_stop(value);
  // @@protoc_insertion_point(field_set:transport_catalogue_proto.StopCoords.stop)
}

// .svg_proto.Point point = 2;
inline bool StopCoords::_internal_has_point() const {
  return this != internal_default_instance() && _impl_.point_ != nullptr;
}
inline bool StopCoords::has_point() const {
  return _internal_has_point();
}
inline const ::svg_proto::Point& StopCoords::_internal_point() const {
  const ::svg_proto::Point* p = _impl_.point_;
  return p != nullptr ? *p : reinterpret_cast<const ::svg_proto::Point&>(
      ::svg_proto::_Point_default_instance_);
}
inline const ::svg_proto::Point& StopCoords::point() const {
  // @@protoc_insertion_point(field_get:transport_catalogue_proto.StopCoords.point)
  return _internal_point();
}
inline void StopCoords::unsafe_arena_set_allocated_point(
    ::svg_proto::Point* point) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.point_);
  }
  _impl_.point_ = point;
  if (point) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:transport_catalogue_proto.StopCoords.point)
}
inline ::svg_proto::Point* StopCoords::release_point() {
  
  ::svg_proto::Point* temp = _impl_.point_;
  _impl_.point_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::svg_proto::Point* StopCoords::unsafe_arena_release_point() {
  // @@protoc_insertion_point(field_release:transport_catalogue_proto.StopCoords.point)
  
  ::svg_proto::Point* temp = _impl_.point_;
  _impl_.point_ = nullptr;
  return temp;
}
inline ::svg_proto::Point* StopCoords::_internal_mutable_point() {
  
  if (_impl_.point_ == nullptr) {
    auto* p = CreateMaybeMessage<::svg_proto::Point>(GetArenaForAllocation());
    _impl_.point_ = p;
  }
  return _impl_.point_;
}
inline ::svg_proto::Point* StopCoords::mutable_point() {
  ::svg_proto::Point* _msg = _internal_mutable_point();
  // @@protoc_insertion_point(field_mutable:transport_catalogue_proto.StopCoords.point)
  return _msg;
}
inline void StopCoords::set_allocated_point(::svg_proto::Point* point) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.point_);
  }
  if (point) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(point));
    if (message_arena != submessage_arena) {
      point = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, point, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.point_ = point;
  // @@protoc_insertion_point(field_set_allocated:transport_catalogue_proto.StopCoords.point)
}

// -------------------------------------------------------------------

// MapRenderer

// .transport_catalogue_proto.RenderSettings render_settings = 1;
inline bool MapRenderer::_internal_has_render_settings() const {
  return this != internal_default_instance() && _impl_.render_settings_ != nullptr;
}
inline bool MapRenderer::has_render_settings() const {
  return _internal_has_render_settings();
}
inline void MapRenderer::clear_render_settings() {
  if (GetArenaForAllocation() == nullptr && _impl_.render_settings_ != nullptr) {
    delete _impl_.render_settings_;
  }
  _impl_.render_settings_ = nullptr;
}
inline const ::transport_catalogue_proto::RenderSettings& MapRenderer::_internal_render_settings() const {
  const ::transport_catalogue_proto::RenderSettings* p = _impl_.render_settings_;
  return p != nullptr ? *p : reinterpret_cast<const ::transport_catalogue_proto::RenderSettings&>(
      ::transport_catalogue_proto::_RenderSettings_default_instance_);
}
inline const ::transport_catalogue_proto::RenderSettings& MapRenderer::render_settings() const {
  // @@protoc_insertion_point(field_get:transport_catalogue_proto.MapRenderer.render_settings)
  return _internal_render_settings();
}
inline void MapRenderer::unsafe_arena_set_allocated_render_settings(
    ::transport_catalogue_proto::RenderSettings* render_settings) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.render_settings_);
  }
  _impl_.render_settings_ = render_settings;
  if (render_settings) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:transport_catalogue_proto.MapRenderer.render_settings)
}
inline ::transport_catalogue_proto::RenderSettings* MapRenderer::release_render_settings() {
  
  ::transport_catalogue_proto::RenderSettings* temp = _impl_.render_settings_;
  _impl_.render_settings_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::transport_catalogue_proto::RenderSettings* MapRenderer::unsafe_arena_release_render_settings() {
  // @@protoc_insertion_point(field_release:transport_catalogue_proto.MapRenderer.render_settings)
  
  ::transport_catalogue_proto::RenderSettings* temp = _impl_.render_settings_;
  _impl_.render_settings_ = nullptr;
  return temp;
}
inline ::transport_catalogue_proto::RenderSettings* MapRenderer::_internal_mutable_render_settings() {
  
  if (_impl_.render_settings_ == nullptr) {
    auto* p = CreateMaybeMessage<::transport_catalogue_proto::RenderSettings>(GetArenaForAllocation());
    _impl_.render_settings_ = p;
  }
  return _impl_.render_settings_;
}
inline ::transport_catalogue_proto::RenderSettings* MapRenderer::mutable_render_settings() {
  ::transport_catalogue_proto::RenderSettings* _msg = _internal_mutable_render_settings();
  // @@protoc_insertion_point(field_mutable:transport_catalogue_proto.MapRenderer.render_settings)
  return _msg;
}
inline void MapRenderer::set_allocated_render_settings(::transport_catalogue_proto::RenderSettings* render_settings) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete _impl_.render_settings_;
  }
  if (render_settings) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(render_settings);
    if (message_arena != submessage_arena) {
      render_settings = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, render_settings, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.render_settings_ = render_settings;
  // @@protoc_insertion_point(field_set_allocated:transport_catalogue_proto.MapRenderer.render_settings)
}

// repeated .transport_catalogue_proto.StopCoords stops_coords = 2;
inline int MapRenderer::_internal_stops_coords_size() const {
  return _impl_.stops_coords_.size();
}
inline int MapRenderer::stops_coords_size() const {
  return _internal_stops_coords_size();
}
inline void MapRenderer::clear_stops_coords() {
  _impl_.stops_coords_.Clear();
}
inline ::transport_catalogue_proto::StopCoords* MapRenderer::mutable_stops_coords(int index) {
  // @@protoc_insertion_point(field_mutable:transport_catalogue_proto.MapRenderer.stops_coords)
  return _impl_.stops_coords_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::transport_catalogue_proto::StopCoords >*
MapRenderer::mutable_stops_coords() {
  // @@protoc_insertion_point(field_mutable_list:transport_catalogue_proto.MapRenderer.stops_coords)
  return &_impl_.stops_coords_;
}
inline const ::transport_catalogue_proto::StopCoords& MapRenderer::_internal_stops_coords(int index) const {
  return _impl_.stops_coords_.Get(index);
}
inline const ::transport_catalogue_proto::StopCoords& MapRenderer::stops_coords(int index) const {
  // @@protoc_insertion_point(field_get:transport_catalogue_proto.MapRenderer.stops_coords)
  return _internal_stops_coords(index);
}
inline ::transport_catalogue_proto::StopCoords* MapRenderer::_internal_add_stops_coords() {
  return _impl_.stops_coords_.Add();
}
inline ::transport_catalogue_proto::StopCoords* MapRenderer::add_stops_coords() {
  ::transport_catalogue_proto::StopCoords* _add = _internal_add_stops_coords();
  // @@protoc_insertion_point(field_add:transport_catalogue_proto.MapRenderer.stops_coords)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::transport_catalogue_proto::StopCoords >&
MapRenderer::stops_coords() const {
  // @@protoc_insertion_point(field_list:transport_catalogue_proto.MapRenderer.stops_coords)
  return _impl_.stops_coords_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace transport_catalogue_proto

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_map_5frenderer_2eproto
